<?php
        delete_option('loglog_def_style');
        delete_option('loglog_def_mojiiro');
        delete_option('loglog_def_hukidasi');
        delete_option('loglog_kaimei');
        delete_option('loglog_name_color');
        delete_option('loglog_hatugen_color');
        delete_option('loglog_tokuteitango_henkou');
        delete_option('loglog_tokuteitango_color');
        delete_option('loglog_hukidasi_color');
        delete_option('aoringolog_installed');
?>
